sudo: required
services:
  - docker

before_install:
  - docker build -t carlosalonsogtz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true carlosalonsogtz/react-test npm test

after_success:
  - docker build -t carlosalonsogtz/multi-client-v2 ./client
  - docker build -t carlosalonsogtz/multi-server-v2 ./server
  - docker build -t carlosalonsogtz/multi-worker-v2 ./worker
  - docker build -t carlosalonsogtz/multi-nginx-v2 ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin

  - docker push carlosalonsogtz/multi-client-v2
  - docker push carlosalonsogtz/multi-server-v2
  - docker push carlosalonsogtz/multi-worker-v2
  - docker push carlosalonsogtz/multi-nginx-v2